---
# - name: Ensure Docker is installed
#   apt:
#     name: docker.io
#     state: present
#   become: true

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Create application directories
  file:
    path: "{{ microbank_base_dir }}/{{ item }}"
    state: directory
    owner: "{{ microbank_user }}"
    mode: "0755"
  loop:
    - configs
    - logs
    - data
  become: true

- name: Deploy environment configuration
  template:
    src: environment.yaml.j2
    dest: "{{ microbank_base_dir }}/configs/environment.yml"
    owner: "{{ microbank_user }}"
    mode: "0644"
  notify: Restart MicroBank services
  become: true
