events {
   worker_connections 1024;
}

http {
    upstream account_service {
        server account-service:8080;
    }

    upstream transaction_service {
        server transaction-service:8081;
    }

    server {
        listen 80;
        server_name localhost;

        location /api/accounts {
            proxy_pass http://account_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/transactions {
            proxy_pass http://transaction_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}