events {
   worker_connections 1024;   # Max simultaneos connections
}

http {
    # Upstream servers - where Ngins forwards requests
    upstream account_service {
        server account-service:8080;    # Docker service name + port
    }

    upstream transactio_service {
        server transaction-service:8081;
    }

    server {
        listen 80;     # Nginx listens on port 80
        server_name localhost;

        # Route /api/accounts/* to Account Service
        location /api/accounts {
            proxy_pass http://account_service;
        }

        # Route /api/transaction/* to Transaction Service
        location /api/transaction {
            proxy_pass http://transaction_service;
        }

        # Health check endpoint
        location /health {
            return 200 'OK';
      }
  }
}
