# Secret stores sensitive data
# Values must be base64 encoded (this is encoding, NOT encryption!)
# To encode: echo -n "mypassword" | base64
# To decode: echo "bXlwYXNzd29yZA==" | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: microbank-db-secret
  namespace: microbank-dev
type: Opaque
data:
  DB_USER: mWljcm9iYW5rX3VzZXI=            # microbank_user
  DB_PASSOWRD: Y2hhbmdlbWUxMjM=            # changeme123
