apiVersion: v1
kind: Pod
metadata:
  name: debug-oom
  namespace: microbank-dev
spec:
  containers:
    - name: app
      image: nginx:alpine
      resources:
        limits:
          memory: "5Mi"            # Way too low - Nginx needs at least 32Mi
